pluginGroup = com.shuzijun.markdown
pluginName = markdown-editor
pluginVersion = 2.0.6
pluginRepositoryUrl = https://github.com/shuzijun/markdown-editor

pluginSinceBuild = 261.0
pluginUntilBuild =

platformType = IU
platformVersion = 2026.2

runIdeJvmArgs=-Dfile.encoding=utf-8,-Dide.browser.jcef.log.level=verbose
